### ISSUE TITLE
on Windows 10, cmake --build build --config Release --target ovpncli fails

### ISSUE THREAD

**Issue by datajango** [OpenVPN/openvpn3#156] opened 2021-04-15 09:30 UTC
wintun and tap are missing.

G:\dv\openvpn\openvpn3\cmake\..\openvpn/tun/win/client/tunsetup.hpp(149,7): error C2065: 'wintun': undeclared identifier [G:\dv\openvpn\build\test
\ovpncli\ovpncli.vcxproj]
G:\dv\openvpn\openvpn3\cmake\..\openvpn/tun/win/client/tunsetup.hpp(149,17): error C2065: 'tap': undeclared identifier [G:\dv\openvpn\build\test\o
vpncli\ovpncli.vcxproj]
G:\dv\openvpn\openvpn3\cmake\..\openvpn/tun/win/client/tunsetup.hpp(150,20): error C2065: 'tap': undeclared identifier [G:\dv\openvpn\build\test\o
vpncli\ovpncli.vcxproj]

**Comment by lstipakov** [comment] 2021-04-16 06:28
Indeed, thanks for spotting this. We've committed the fix to our internal SCM, will push to github soonish.

```
diff --git a/openvpn/tun/win/client/tunsetup.hpp b/openvpn/tun/win/client/tunsetup.hpp
index 6bb7d6f1..c091778a 100644
--- a/openvpn/tun/win/client/tunsetup.hpp
+++ b/openvpn/tun/win/client/tunsetup.hpp
@@ -146,8 +146,8 @@ namespace openvpn {
        if (ring_buffer)
          register_rings(th(), ring_buffer);

-       if (!wintun && tap.index_defined())
-         Util::flush_arp(tap.index, os);
+       if (tun_type_ == Type::TapWindows6 && tap_.index_defined())^M
+         Util::flush_arp(tap_.index, os);^M

        return th.release();
       }
```

**Comment by dsommers** [comment] 2021-04-20 22:34
Commit 6da31163f69fc706fe0d should resolve this issue.  Closing it now, please reopen if the issue is still present.

**Closed by dsommers** 2021-04-20 22:34 UTC
