### ISSUE TITLE
how to install openvpn3 clinet on raspberry 4B buster armhf？

### ISSUE THREAD

**Issue by zouzhe1** [OpenVPN/openvpn3#176] opened 2021-09-30 05:56 UTC
https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux?_ga=2.155723899.1768139803.1632980211-1432597796.1630572393

https://openvpn.net/cloud-docs/openvpn-3-client-for-linux/

this  link  cannot  run in armhf

**Comment by dsommers** [comment] 2021-10-04 14:09
Closing, as this is a duplicate of https://github.com/OpenVPN/openvpn3-linux/issues/77

**Closed by dsommers** 2021-10-04 14:09 UTC
