### ISSUE TITLE
Cannot move Client class def/impl to separate files.

### ISSUE THREAD

**Issue by imalyavskiy** [OpenVPN/openvpn3#62] opened 2018-12-19 13:36 UTC
Hello I would like to use several cpp files to build this and dependent project. But currently cannot do this because if to include opnvpn headers into at least two cpp files the linker angries with a lot of "already defined in cli.obj" errors. What is the reason for the headers to be designed in this way or is there any way to use the headers in desired manner without changing them? 

Thanks in advance.

PS: Working on Win 10.

**Comment by schwabe** [comment] 2018-12-19 13:54
Duplicate of #48. See also the openvpn3-linux client as example how to use multiple cpp files and including openvpn3 only once.

**Closed by schwabe** 2018-12-19 13:54 UTC

**Comment by imalyavskiy** [comment] 2018-12-20 08:53
Thanks a lot!
