### ISSUE TITLE
addr_pair_mask_parse_error

### ISSUE THREAD

**Issue by oawang** [OpenVPN/openvpn3#189] opened 2021-12-27 11:25 UTC
exception parsing IPv4 route: [route] [mysql.rds.aliyuncs.com] [255.255.255.255] [vpn_gateway]  : addr_pair_mask_parse_error: AddrMaskPair parse error 'route': mysql.rds.aliyuncs.com/255.255.255.255 : ip_exception: error parsing route IP address 'mysql.rds.aliyuncs.com' : An invalid argument was supplied.

**Comment by oawang** [comment] 2021-12-27 11:25
allow-pull-fqdn

push "route mysql.rds.aliyuncs.com 255.255.0.0"

**Comment by oawang** [comment] 2021-12-27 11:31
vpn client:
windows openvpn3

**Comment by schwabe** [comment] 2021-12-27 13:56
duplicate of #163

**Closed by schwabe** 2021-12-27 13:56 UTC

**Comment by oawang** [comment] 2021-12-28 06:52
Without this configuration, same error reported

**Comment by oawang** [comment] 2021-12-28 06:52
allow-pull-fqdn
Without this configuration, same error reported

**Comment by schwabe** [comment] 2021-12-28 14:29
domain names in route statements are not supported in openvpn3 and will probably never be as this is a very fragile feature.

**Comment by oawang** [comment] 2021-12-30 11:16
Is there another solution?

**Comment by oawang** [comment] 2021-12-30 11:16
> domain names in route statements are not supported in openvpn3 and will probably never be as this is a very fragile feature.

Is there another solution?
