### ISSUE TITLE
parse domain name error

### ISSUE THREAD

**Issue by oawang** [OpenVPN/openvpn3#190] opened 2021-12-28 09:19 UTC
exception parsing IPv4 route: [route] [mysql.rds.aliyuncs.com] [255.255.255.0] [vpn_gateway] : addr_pair_mask_parse_error: AddrMaskPair parse error 'route': mysql.rds.aliyuncs.com/255.255.255.0 : ip_exception: error parsing route IP address 'mysql.rds.aliyuncs.com' : Invalid argument

Without this configuration[allow-pull-fqdn], same error reported

**Comment by oawang** [comment] 2021-12-28 09:21
client
dev tun
proto tcp
route-nopull
route-metric 200

dhcp-option DNS 8.8.8.8
dhcp-option DNS 4.4.4.4
route 172.16.0.0 255.255.0.0 vpn_gateway
route 192.168.0.0 255.255.255.0 vpn_gateway
route mysql.rds.aliyuncs.com 255.255.255.0 vpn_gateway

...
...

**Comment by schwabe** [comment] 2021-12-28 14:30
still a duplicate of #163 

Please do not open duplicate tickets

**Closed by schwabe** 2021-12-28 14:30 UTC

**Comment by oawang** [comment] 2021-12-29 02:09
Without this configuration[  allow-pull-fqdn  ], same error reported
