### ISSUE TITLE
--response (for auth token) not working

### ISSUE THREAD

**Issue by kromwelr** [OpenVPN/openvpn3#69] opened 2019-05-11 16:24 UTC
the latest version (or maybe not)  is not accepting --reponse where the auth token goes to. i made a script to include the token via ovpncli it has been working for a long time until yesterday's update of the vpn. what happened here?

ovpncli -t UR> -u USER -p PASSWORD --response=AUTH_TOKEN connect

**Comment by schwabe** [comment] 2019-05-13 11:36
I am not sure what you are trying to do here. The argument for `--timeout` (`-t`) looks very wrong with `UR>`. Also `--response` is related to dynamic challenge/response rather than to auth-token. 

So could please eloberate  bit on what you are trying to achieve since I do not really understand what you are doing.

**Comment by dsommers** [comment] 2019-05-13 19:08
When you say AUTH_TOKEN ... what are you referring to in this context?

The term "auth token" is a very specific OpenVPN feature which happens under the hood, which basically ends up in the password field after successful authentication. The contents of the 'auth-token' is pushed by the OpenVPN server and cannot be provided by any configuration file.  Which is what @schwabe refers to.

Now, I do see in the code that --response is tied to the static/dynamic challenge feature, which is used for OTP support.  So if AUTH_TOKEN is referring to an OTP token, this makes somewhat more sense. 

But to be able to fully understand what broke when, can you please provide a commit reference to where it worked and then confirm the commit of the broken version?

**Comment by kromwelr** [comment] 2019-05-14 00:26
> I am not sure what you are trying to do here. The argument for `--timeout` (`-t`) looks very wrong with `UR>`. Also `--response` is related to dynamic challenge/response rather than to auth-token.
> 
> So could please eloberate bit on what you are trying to achieve since I do not really understand what you are doing.

**-t is for timeout? i suggest you google more.**

**Comment by kromwelr** [comment] 2019-05-14 00:39
> When you say AUTH_TOKEN ... what are you referring to in this context?
> 
> The term "auth token" is a very specific OpenVPN feature which happens under the hood, which basically ends up in the password field after successful authentication. The contents of the 'auth-token' is pushed by the OpenVPN server and cannot be provided by any configuration file. Which is what @schwabe refers to.
> 
> Now, I do see in the code that --response is tied to the static/dynamic challenge feature, which is used for OTP support. So if AUTH_TOKEN is referring to an OTP token, this makes somewhat more sense.
> 
> But to be able to fully understand what broke when, can you please provide a commit reference to where it worked and then confirm the commit of the broken version?

Yes you are right that im referring to otp token. i was able to create a script that gets OTP first via GoogleAPI then include that OTP in my ovpncli connection call.

`@ECHO OFF 
REM Turning off system out - @ECHO OFF

for /f %%i in ('authenticator --account <ACCOUNT> --key <KEY>') do set token=%%i
REM GET Token from Google authenticator CLI using account name and secret key. Set token to %token% variable

echo %token% | clip
ovpncli -t <TARGETURL> -u <USERNAME> -p <PASSWORD> --response=%token% connect
REM call openVPN via CLI providing username, password and the token from Google authenticator`

i am pretty sure that this is 100% working as I am using this since November 2018. for the commit reference, i don't really follow the update details that's why i posted here to get opinion from you guys. The only thing i remember is that there a vpn server upgrade though i don't know the details of that either. 

Right now, when i run the above command, i am asked to input the OTP manually in the command prompt whereas this should be automatically included via the --response flag.

Thanks for your support.

**Comment by schwabe** [comment] 2019-05-14 09:05
> **-t is for timeout? i suggest you google more.**

Do not be rude. But -t is really for timeout in the ovpncli tool:
`
      std::cout << "--timeout, -t         : timeout" << std::endl;
`

So I have the feeling since the name ovpncli is a bit generic, you talking about some other `ovpncli` tool. For the context of this repository however `ovpncli` is the tool that is found under `test/ovpncli/`

The usage you use will not work with the ovpncli tool that is in repository. So you need to have more context since I think you are talking about some other tool that just happens to be also called `ovpncli`

**Comment by dsommers** [comment] 2019-05-14 18:49
This syntax here you refer to here: ` ovpncli -t -u -p --response=%token% connect` is not something which matches the intended behaviour of [test/ovpncli/cli.cpp](https://github.com/OpenVPN/openvpn3/blob/master/test/ovpncli/cli.cpp).

The `-t`, `-u` and `-p` arguments all expects an argument value.  So it should be something like:

    ./ovpncli -t 120 -u testuser -p mys3cretp4ssw0wd

On top of that, you have a `connect` argument which makes absolutely no sense.  And you are lacking a reference to an `.ovpn` configuration profile it should use.

Further, [test/ovpncli/cli.cpp](https://github.com/OpenVPN/openvpn3/blob/master/test/ovpncli/cli.cpp) has seen some updates since November 2018.  But none of these changes are related to the command line argument parser.  The first commit which touches the command line parsing logic is commit 59de63fa657990f27a92962399b0b16dbb928e75, from March 10, 2018.  So based on the information you've provided here, it really looks like you're using a different `ovpncli` utility than the one we are providing as a reference and test client based on the OpenVPN 3 Core Library.

Closing this issue now.  The issue can be re-opened if new details arrives which confirms issues when this projects `ovpncli` utility is used correctly.

**Closed by dsommers** 2019-05-14 18:49 UTC
